#!/bin/sh

# Script này để cấu hình 2 màn hình
# 1 - Lap
# 2 - Màn hình tại nhà (1280 x 1024)
# Cơ chế - bên phải màn hình chính

xrandr --output LVDS1 --mode 1366x768 --left-of VGA1
xrandr --output VGA1 --mode 1280x1024 --right-of LVDS1
echo done
