#!/bin/sh

# Script này để cấu hình 2 màn hình
# 1 - Lap
# 2 - Màn hình tại nhà (1280 x 1024)
# Cơ chế - bên phải màn hình chính

xrandr --output HDMI1 --primary
# xrandr --output VGA1 --primary
# xrandr --output LVDS1 --mode 1366x768 --right-of VGA1
# xrandr --output VGA1 --mode 1280x800 --right-of LVDS1
# xrandr --output VGA1 --mode "1280x800_60.00" --right-of LVDS1
xrandr --output HDMI1 --mode 1920x1080 --right-of LVDS1
# xrandr --output VGA1 --mode 1920x1080 --left-of LVDS1
# xrandr --output HDMI1 --mode 1920x1080 --left-of VGA1
xrandr --output LVDS1 --mode 1366x768  --left-of HDMI1
# xrandr --output VGA1  --mode 1920x1080 --right-of LVDS1
# xrandr --output HDMI1 --mode 1920x1080 --left-of VGA1


echo done
