echo '0' > '/proc/sys/kernel/nmi_watchdog'
echo '1' > '/sys/module/snd_hda_intel/parameters/power_save'
echo 'min_power' > '/sys/class/scsi_host/host1/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host2/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host3/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host4/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host5/link_power_management_policy'
echo 'min_power' > '/sys/class/scsi_host/host0/link_power_management_policy'
echo '1500' > '/proc/sys/vm/dirty_writeback_centisecs'
echo 'auto' > '/sys/bus/i2c/devices/i2c-1/device/power/control'
echo 'auto' > '/sys/bus/usb/devices/1-1.4/power/control'
echo 'auto' > '/sys/bus/usb/devices/3-1/power/control'
ethtool -s eno1 wol d;
echo 'auto' > '/sys/bus/pci/devices/0000:0c:00.1/power/control'
echo 'auto' > '/sys/bus/pci/devices/0000:01:00.1/power/control'
